### ISSUE TITLE
reqHistoricalData missing input in the example in documentation

### ISSUE THREAD

**Issue by ecpgieicg** [softwarespartan/IB4m#53]
Hi Abel,

Thank you for creating and sharing this package.

FYI, v9.72+ reqHistoricalData() requires an additional boolean before the empty list in the input. (Stipulated [here](https://interactivebrokers.github.io/tws-api/classIBApi_1_1EClient.html#a5eac5b7908b62c224985cf8577a8350c).) So in the [example](http://softwarespartan.github.io/IB4m/docs/html/HistoricalDataExample.html), 

    session.eClientSocket.reqHistoricalData(1000001,contract,'20141230 16:00:00','1 Y','1 day','TRADES',1,1,[]); pause(0.5);

would need to be replaced with 

    session.eClientSocket.reqHistoricalData(1000001,contract,'20141230 16:00:00','1 Y','1 day','TRADES',1,1,false,[]); pause(0.5);

Your package itself still works smoothly.

Cheers

**Comment by GIL1105** [comment]
Indeed by adding "false" I get a better result

But still have a problem

I have connected Matlab to TWS, all seems OK because AccountSummaryExample returns all the info about my IB account

Then I execute contract = com.tws.ContractFactory.GenericStockContract('FB');

and get the variable contract well filled in:

val =
 conid	0
symbol	FB
strike	0.0
exchange	SMART
currency	USD
primaryExch	ISLAND

Then I execute session.eClientSocket.reqHistoricalData(1000001,contract,'20141230 16:00:00','1 Y','1 day','TRADES',false,1,1,[]);

but get the following error:

1000001 321 Error validating request:-'bP' : cause - Please enter a valid security type

Why is the stock FB invalid here ?

**Comment by ecpgieicg** [comment]
You need to specify the security type. I am not with my computer atm. If memory serves, it's either STK or STOCK. Let me know if you can make it work.

**Comment by GIL1105** [comment]
Thank you for helping
I forced STK into contract and stopped getting the invalid security error, sounds good
But I got another error:  enddates not supported with live updates

Please see below my short session:

>> clear
>> session = TWS.Session.getInstance();
session.eClientSocket.eConnect('127.0.0.1',7496,0);
-1 2104 Market data farm connection is OK:hfarm
 
-1 2104 Market data farm connection is OK:eufarm
 
-1 2104 Market data farm connection is OK:usfarm.nj
 
-1 2104 Market data farm connection is OK:jfarm
 
-1 2104 Market data farm connection is OK:usfuture
 
-1 2104 Market data farm connection is OK:cashfarm
 
-1 2104 Market data farm connection is OK:usfarm
 
-1 2106 HMDS data farm connection is OK:euhmds
 
-1 2106 HMDS data farm connection is OK:fundfarm
 
-1 2106 HMDS data farm connection is OK:ushmds
 
>> [buf,lh] = TWS.initBufferForEvent(TWS.Events.HISTORICALDATA);
contract = com.tws.ContractFactory.GenericStockContract('FB');
>> contract.secType('STK');

>> session.eClientSocket.reqHistoricalData(1000001,contract,'20181230 16:00:00','1 Y','1 day','TRADES',false,1,1,[]);
1000001 321 Error validating request:-'bP' : cause - End date not supported with live updates

**Comment by softwarespartan** [comment]
You should follow the example in docs.  Not sure why you are using contract
factory.  Please open a separate issue

**Comment by softwarespartan** [comment]
Be sure to initialize contracts as specified in the docs and as we discussed in your email yesterday 

contract = com.ib.client.Contract();
contract.symbol('FB')
contract.exchange('SMART');
contract.primaryExch('ISLAND');
contract.currency('USD');
contract.secType('STK');

**Comment by softwarespartan** [comment]
@ecpgieicg looks like I didn't update the `html` when I did the code updates for v9.73.  The actual codes (*.m) in the `docs` folder have been updated but the html is stale.  I'll try to get that regenerated soon. Apologies for the confusion.

**Comment by GIL1105** [comment]
I’m away from my PC for hours
Back this evening for further discussing
Thanks for helping
Gilles

**Comment by ecpgieicg** [comment]
Sounds good. Cheers

**Comment by GIL1105** [comment]
Abel,

That’s because on your github page you don’t tell to go to the docs, so I start with the github pages, which seem incomplete
I see I am not the only one who follows this path

I’m through your marketdataexample.m and the instruction below seems not working because of .m_ , correct ?
contract.m_exchange = 'ARCA';  contract.m_primaryExch = 'ARCA';

Gilles

**Comment by softwarespartan** [comment]
please open a separate ticket.  thanks

**Comment by GIL1105** [comment]
OK
Let me first scroll down all you script, the ticket could be about selected instructions in this script
