### ISSUE TITLE
Not an issue but a question: How to start/handle simultaneous market data streams

### ISSUE THREAD

**Issue by OlafZielke-EQ** [softwarespartan/IB4m#84]
Hi Abel,
Thanks a lot for providing your codes to the community! Very much appreciated.

I just started using IB4m and work my way trough the examples that you provide, currently looking at streaming market data. In your example “MarketDataExample.m”, you mention something about the additional book keeping that is necessary when having multiple market data subscriptions open simultaneously (using HashMaps). The concept (e.g., HashMaps) is new to me and I’m struggling to make progress with only the information in the example file.

So, here my questions:
How to actually start multiple streams? I could do so in a loop but that doesn’t feel right. Is there another way to start them within the same function call (e.g., by passing more than one contract to it, each with its own reqId)?
Once that is done, what to do then (i.e., how  to further process that stream)?

a bit of sample code would be great :)

Thanks in advance and kind regards,
-olaf

**Comment by Despair2000** [comment]
You can subscribe to several market data streams (I had up to 100 subscriptions running without problems which is the limit without booster packet). Simply assign a different reqId to each stream somehow like this:

`[buffer, listener] = TWS.initMarketDataBufferWithReqId(50,reqID);  reqMktData(session.eClientSocket,reqID,.contract,'',false,false,[]);`

Using hashmaps like Abel suggests in the example is surely more efficient but I didn't know how to implement this either. Maybe @softwarespartan wants to enlighten us with an example? :-)

**Comment by OlafZielke-EQ** [comment]
thanks for the quick reply.
Your approach seems to be the most straightforward way to do it. Guess I'll follow it until I/we learn more about hash maps etc.
cheers

**Comment by softwarespartan** [comment]
The hash map approach is to just have single listener that packs the data across all requests into a single hash map 

`buf = map(event.data.reqId); buf.add(event.data)`

or just

`map(event.data.reqId).add(event.data)`

The hash map can be initialized as 

`containers.Map('KeyType','double','ValueType','any')`

I use this solution a lot since all the market data streams end up in a single object.  Otherwise, have many buffers all over the place and can easy to mix them up if not careful.

The full treatment can be found in IB4m at `TWS.MarketData.EventHandler`

Feel free to reopen if have more questions on this.
